### ISSUE TITLE
Integration tests failing with kotlin M12

### ISSUE THREAD

**Issue by rosadam** [prezi/spaghetti#194]
With [Kotlin M12](https://github.com/JetBrains/kotlin/releases/tag/build-0.12.200) integration tests are failing:

```
:spaghetti-kotlin-support:integTest

com.prezi.spaghetti.kotlin.KotlinGeneratorIntegrationTest > test harness FAILED
    java.lang.RuntimeException at KotlinGeneratorIntegrationTest.groovy:33

1 test completed, 1 failed
:spaghetti-kotlin-support:integTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spaghetti-kotlin-support:integTest'.
> There were failing tests. See the report at: file:///Users/rosadam/work/tools/spaghetti/spaghetti-kotlin-support/build/reports/tests/index.html
```

```
java.lang.RuntimeException: Executing /Users/rosadam/Downloads/kotlinc/bin/kotlinc-js -output /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/compiled.js -library-files /Users/rosadam/Downloads/kotlinc/lib/kotlin-jslib.jar -output-prefix build/kotlinjs/kotlin.js /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/__TestModuleInit.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/__TestModuleProxy.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/dependency/DependencyModule.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/dependency/Fruit.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/dependency/Point2d.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/dependency/Prime.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/Numbers.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/Point3d.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/headers/spaghetti/test/Spaghetti.kt /var/folders/59/m63jslx15wl6d6c78769qb400000gn/T/1433509458342-0/sources/spaghetti/test/TestModule.kt returned error code: 1
	at com.prezi.spaghetti.generator.test.LanguageSupportSpecification.executeIn(LanguageSupportSpecification.groovy:125)
	at com.prezi.spaghetti.generator.test.LanguageSupportSpecification.execute(LanguageSupportSpecification.groovy:113)
	at com.prezi.spaghetti.kotlin.KotlinGeneratorIntegrationTest.compile(KotlinGeneratorIntegrationTest.groovy:33)
	at com.prezi.spaghetti.generator.test.LanguageSupportSpecification.test harness(LanguageSupportSpecification.groovy:65)
```

M11 works fine.

**Comment by lptr** [comment]
On it

**Comment by knuton** [comment]
Maybe we should version the language plugins independently to allow them to track language development.

**Comment by lptr** [comment]
That was always the plan, but the API had to be solidified a bit before that. Now would be a good time to do it perhaps. But let's merge the API refactor branch in first.
